# Generated by Django 4.2.2 on 2023-06-27 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('birthday', models.DateField()),
                ('address', models.CharField(max_length=500)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=25)),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_image')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='classes.class')),
            ],
        ),
    ]
